linux/ena: Add DEFINE_SHOW_ATTRIBUTE support for older kernels
`DEFINE_SHOW_ATTRIBUTE` was introduced in Kernel 4.16 (See [1]).
`DEFINE_SHOW_ATTRIBUTE` is used in debugfs to access PHC statistics.
For kernels older than 4.16, compilation fails when PHC
is compiled in (Using `ENA_PHC_INCLUDE=1`).

The compilation failure:

ena_debugfs.c:45:1: warning: data definition has no type or storage class
DEFINE_SHOW_ATTRIBUTE(phc_stats);
^~~~~~~~~~~~~~~~~~~~~
.../ena_debugfs.c:45:1: error: type defaults to ‘int’ in declaration of ‘DEFINE_SHOW_ATTRIBUTE’ [-Werror=implicit-int]

This patch adds a kcompat.h entry which contains the
definition of `DEFINE_SHOW_ATTRIBUTE` in case it is not
defined.

[1]: https://github.com/torvalds/linux/commit/a08f06bb7a0743a7fc8d571899c93d882468096e
Signed-off-by: David Arinzon <darinzon@amazon.com>